### ISSUE TITLE
Download of OuterHull and Gyrification packages

### ISSUE THREAD

**Issue by urrand** [ilwoolyu/LocalGyrificationIndex#1]
Hey, among the required packages I found klaplace and CurveExtraction but not OuterHull and Gyrification...where am I supposed to get those?

Thank you,
A

**Comment by ilwoolyu** [comment]
They all are in this repo. You can find MATLAB implementation in `matlab` and Gyrification is `src` (core implementation) and `wrapper` (user interface). They need to be compiled with [MATLAB compiler](https://www.mathworks.com/products/compiler.html) and [CMake](https://cmake.org/) prior to calling `lgi` in `script`. If you like to use precompiled version, please find it at at [Docker](https://hub.docker.com/r/ilwoolyu/cmorph/) or [Singularity](https://vanderbilt.box.com/v/cmorph-release).

**Comment by urrand** [comment]
Can you list the compilation steps? Cause I got errors when I try to compile Gyrification code...
